build:
  stage: build
  image: secondstate/ssvm:ubuntu-build
  before_script:
    - rm -rf build
    - mkdir build
    - cd build
  script:
    - cmake ..
    - make
  cache:
    paths:
      - build
    policy: push

test:
  stage: test
  image: secondstate/ssvm:ubuntu-build
  before_script:
    - cd build
  script:
    - cmake .. -DBUILD_TESTS=ON
    - make
    - cd test/loader
    - ./ssvmLoaderEthereumTests
    - ./ssvmLoaderFileMgrTests
    - ./ssvmLoaderWagonTests
    - cd ../ast/load
    - ./ssvmASTLoadTests
    #- cd ../../evm
    #- ./ssvmEVMTests
    - cd ../../evmc
    - ./ssvmEVMCTests
    - cd ../proxy
    - ./ssvmProxyTests
    - cd ../expected
    - ./expectedTests
  cache:
    paths:
      - build
    policy: pull
